### ISSUE TITLE
Marker Mouse-over Display Modal

### ISSUE THREAD

**Issue by testmonkey101** [ndnumobile/web#138]
On hover of a marker, the modal should display.

Details on Implementation: https://www.mapbox.com/mapbox-gl-js/example/popup-on-hover/

**Comment by zackhitch** [comment]
I figured out a way to do this, but it requires some changes to the way we've created our JSON and made use of our Markers. A new layer is needed to use the standard icon onhover action, but that is preventing onclick from showing the popups. Likely won't be ready for today's presentation, but will keep working on it.

**Comment by zackhitch** [comment]
Completed but not yet pushed.

**Comment by zackhitch** [comment]
not doable
