### ISSUE TITLE
Campus Locations no longer displaying modals. 

### ISSUE THREAD

**Issue by cpin3** [ndnumobile/web#150]
Error recieved 

Uncaught ReferenceError: pressBtnAcademic is not defined
    at HTMLAnchorElement.onclick (mapTest4.html:77)

I'll try to fix it if I can

**Comment by zackhitch** [comment]
the code was commented out for this. The Campus Location buttons need to direct to the building summary modal already in place when you click on a map icon, or to a detail page for locations without a map icon.

**Comment by cpin3** [comment]
OK thanks for the clarification
