### ISSUE TITLE
Change color of Sidebar onhover text

### ISSUE THREAD

**Issue by zackhitch** [ndnumobile/web#263]
<img width="232" alt="screen shot 2017-04-22 at 4 42 40 pm" src="https://cloud.githubusercontent.com/assets/24708484/25309176/c8e39cf4-277a-11e7-8965-45b9c9f6fcb6.png">

I'm thinking white for onhover would be good.

**Comment by zackhitch** [comment]
Not just onhover, but the default text color here for the dropdown should maybe be the standard yellow we use, and onhover could be blue with yellow background or white... Something with more contrast.

**Comment by arpiquette** [comment]
I can take a look at this. Are you saying the campus location names should be yellow?

**Comment by zackhitch** [comment]
The Campus Locations are good, I'm thinking the other items in the sidebar, like for Documents, etc. Should match how the Campus Locations is handled.

**Comment by zackhitch** [comment]
I'm gonna just close this. The colors could be improved, but I think it's perfectly fine for now.
